[package]
name = "fyrstikker"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.5.1"
rstest = "0.11.0"

[dev-dependencies]
criterion = "0.3.5"

[[bench]]
name = "my_benchmark"
harness = false

[profile.release]
opt-level = 3
codegen-units = 1
panic = "abort"
